services:
  backend:
    build: ./backend
    container_name: order-mgmt-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: order-mgmt-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    user: "node"

  db:
    image: postgres:14-alpine
    container_name: order-mgmt-db
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
